### ISSUE TITLE
500 Server Error during upload

### ISSUE THREAD

**Issue by evrhel** [davidpak/SmartNote#12]
Uploading a file to the server results in a `500 Server Error` response, which is unexpected. Encountered on Windows, unknown state on other platforms.

## Steps to Reproduce

1. `cd` into `server/` directory.
2. Start the server using `ant run`.
3. In a separate terminal run `python scripts/upload.py localhost build.xml`.

### `upload.py`
```text
No authentication token provided
Trying to authenticate with server... Done
Upload build.xml... Failed: 500 Server Error
Auth token: None
```

### Server
```text
[java] java.lang.NullPointerException: Cannot read the array length because "<local3>" is null
[java]     at com.smartnote.server.util.FileUtils.getDirectorySize(FileUtils.java:116)
[java]     at com.smartnote.server.auth.Session.writeSessionFile(Session.java:346)
[java]     at com.smartnote.server.api.v1.Upload.handle(Upload.java:53)
[java]     at spark.RouteImpl$1.handle(RouteImpl.java:72)
[java]     at spark.http.matching.Routes.execute(Routes.java:61)
[java]     at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
[java]     at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
[java]     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1598)
[java]     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
[java]     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
[java]     at org.eclipse.jetty.server.Server.handle(Server.java:516)
[java]     at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
[java]     at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
[java]     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
[java]     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
[java]     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
[java]     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
[java]     at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
[java]     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
[java]     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
[java]     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
[java]     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:137)
[java]     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
[java]     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
[java]     at java.base/java.lang.Thread.run(Thread.java:833)
```

### Expected Behavior

The server should be receiving `build.xml` and have it stored in session-protected storage.

**Comment by evrhel** [comment]
Fixed in #13
